config/routes.rb
Rails.application.routes.draw do
  get '/tos', to: 'placeholder#tos'
  get '/privacy', to: 'placeholder#privacy'

  resources :users, only: [:create, :destroy] do
    collection do
      get :sign_out
    end
  end

  root to: 'placeholder#step1'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(email: session[:email]) || User.new
  end
end

app/controllers/placeholder_controller.rb
class PlaceholderController < ApplicationController
  before_filter :set_current_step, only: [:step1, :step2, :step3]
  before_filter :set_current_user, only: [:step1, :step2, :step3]

  def step1
    respond_to do |format|
      format.html { render 'index' }
    end
  end

  def step2
    respond_to do |format|
      format.html { render 'index' }
    end
  end

  def step3
    respond_to do |format|
      format.html { render 'index' }
    end
  end

  def privacy
    respond_to do |format|
      format.html
    end
  end

  def tos
    respond_to do |format|
      format.html
    end
  end

  private

  def set_current_step
    @current_step ||= 1
    @current_step = 2 if session[:email]
    # @current_step = 3 if SESSION[:...] # TODO
  end

  def set_current_user
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ALLOWED_PARAMS = [:email]

  def create
    @user = User.where(user_params).first_or_initialize
    if @user.new_record?
      success = @user.save
    else
      success = true
    end

    respond_to do |format|
      format.html do
        if success
          session[:email] = @user.email
          redirect_to root_path
        else
          @current_step = 1
          render 'placeholder/index'
        end
      end
    end
  end

  def destroy
  end

  def sign_out
    session[:email] = nil

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  private

  def user_params
    params.require(:user).permit(ALLOWED_PARAMS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by(email: session[:email]) || User.new
  end
end

app/helpers/placeholder_helper.rb
module PlaceholderHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AriaFit Sync
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - unless current_user.new_record?
      = link_to 'Sign out', sign_out_users_path, class: 'btn btn-danger'
    = yield

app/views/placeholder/index.html.haml
.container
  .row
    .col-md-12
      %h1 FitAria Sync

      :markdown
        This app will sync your weight only (more data may come in the future, and may include syncing from Fit to FitBit). It will store an entered email address as well as temporary authorizations from Google and FitBit but nothing else is stored on this server.


  #step1.row{class: (@current_step == 1 ? '' : 'hide')}
    .col-md-12
      %h2 Step 1 - Enter your Email Address
      %p This is just to remember your account by. It doesn't have to match your Google or Fitbit account email addresses.

      = simple_form_for @user do |f|
        .form-group
          = f.input :email, label: false, input_html: {class: 'form-control', placeholder: 'E-mail'}

        %button.btn.btn-primary{type: 'submit'}
          Next
          %i.glyphicon.glyphicon-chevron-right

  #step2.row{class: (@current_step == 2 ? '' : 'hide')}
    .col-md-12
      %h2 Step 2 - Authorize Google

      #google-btn
        #my-signin2
      #google-wait.hide
        = image_tag 'ajax_spinner.gif', class: 'img-responsive'
      #google-error.hide
        .alert.alert-danger
      #google-done.hide
        %button.btn.btn-primary
          Next
          %i.glyphicon.glyphicon-chevron-right

  #step3.row{class: (@current_step == 3 ? '' : 'hide')}
    .col-md-12
      %h2 Step 3 - Authorize FitBit

      #fitbit-btn
        = link_to '#', target: '_blank' do
          = image_tag 'fitbit_auth_button.png'
      #fitbit-wait.hide
        = image_tag 'ajax_spinner.gif', class: 'img-responsive'
      #fitbit-error.hide
        .alert.alert-danger
      #fitbit-done.hide
        %button.btn.btn-primary
          %i.glyphicon.glyphicon-ok-circle
          Start Syncing

        :markdown
          _Sync will occur once a day, every day, at midnight. It will not automatically trigger when data changes and will only use what data is available exactly at midnight, every day._

          If sync should fail (for example when your authorization expires after 30 days) you will receive a single email notification allowing you to return here and re-authenticate Google and FitBit to resume sync.

:javascript
  $(Sync.init);

app/views/placeholder/privacy.html.haml
.container
  .row
    .col-md-12
      %h1 Privacy Policy

      :markdown
        The following data is stored in a database:textile

        * Your email address
        * Temporary permission token from Google
        * Temporary permission token from FitBit

        None of your Google Fit data, Fitbit data, account data, IP address, or anything else are stored.

app/views/placeholder/tos.html.haml
.container
  .row
    .col-md-12
      %h1 Terms of Service

      :markdown
        This software is prived as-is with no guarantee whatsoever and may only be used at your own risk.

        Source code for this application may be found at http://github.com/retro486